### ISSUE TITLE
Gem Install Fails

### ISSUE THREAD

**Issue by DonFuego** [contentful/database-exporter.rb#12]
FYI - I'm getting a gem installation failure:

`Installing pg 0.17.1 with native extensions Gem::Ext::BuildError: ERROR: Failed to build gem native extension.`

Running `brew install postgres` seemed to take care of this issue.

**Comment by dlitvakb** [comment]
Hey @DonFuego,

That error happens when you don't have `postgres` installed locally.

Sadly it's not an issue that's solvable through the gem install process

Cheers
