### ISSUE TITLE
Post Gem Install Fails

### ISSUE THREAD

**Issue by DonFuego** [contentful/database-exporter.rb#13]
⇒  gem install database-exporter 
Fetching: database-exporter-0.0.2.gem (100%)
Successfully installed database-exporter-0.0.2
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/todmatth/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/todmatth/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

**Comment by dlitvakb** [comment]
Looks like there's some C binding wrong with the JSON gem on your system.

Please re-install it. This looks to be a common issue across many libraries: https://github.com/bbatsov/rubocop/issues/2512

Cheers

**Comment by DonFuego** [comment]
Yea, oddly - the database exporter was working...then as I tried to connect to the mysql it gave me a libmysqlclient-18.dylib error.  After trying to resolve and create proper symlinks to get the mysql2 gem to connect - the database-exporter executable doesn't load at all.  Just trying to hit reset at this point :/
