### ISSUE TITLE
can't complete steps in README

### ISSUE THREAD

**Issue by ivanoats** [contentful/database-exporter.rb#8]
Step 2 in [README](https://github.com/contentful/database-exporter.rb/blob/master/README.md) has a required dependency of a mapping.json file that is created in step 4?  Could you suggest how to create the mapping.json file before running the command that requires it please?

**Comment by dlitvakb** [comment]
Hey @ivanoats,

Thanks for the input and the related PR #9 

I'll look into fixing the CLI tool to not require the Settings file in the `-h` call rather than changing the documentation.

Cheers
